import { Header } from "@/components/Header/Header";
import "./globals.css";

import { createContext, useContext } from "react";

export const metadata = {
  title: "Hetsaniv_Bike",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
