import { ClerkProvider } from "@clerk/nextjs";
import { Header } from "@/components/Header/Header";
import "./globals.css";

export const metadata = {
  title: "Hetsaniv_Bike",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
